[package]
name = "types_lowering"
version = "0.1.0"
edition = "2024"

[dependencies]
hir = { path = "../hir" }
middle = { path = "../middle" }
ast = { path = "../ast" }
tokens = { path = "../tokens" }