[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
lalrpop-util = "0.20.2"
ast = {path = "../ast"}
tokens = {path = "../tokens"}
lexer = {path = "../lexer"}
pretty_logger = {path = "../pretty_logger"}